baseurl: ""
url: "https://wonderadvisory.com"
permalink: pretty
title: 'Wonder Advisory'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "40px"
  desktop_width: "220px"

home: 
  limit_services: 3

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
      sitemap: false
  - scope:
      path: "**"
    values:
      image: "images/illustrations/pointing.svg"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-last-modified-at # https://github.com/gjtorikian/jekyll-last-modified-at
  - jekyll-seo-tag # https://www.youtube.com/watch?v=7o7DRrCstdo
  - jekyll-sitemap

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
  date-format: '%d-%b-%y'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
